# Generated by Django 4.2.1 on 2023-06-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['num_setor'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
